.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitkincoin_qt test_bitkincoin_qt
clean: FORCE
	$(MAKE) -C .. bitkincoin_qt_clean test_bitkincoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitkincoin_qt_check
bitkincoin-qt bitkincoin-qt.exe: FORCE
	 $(MAKE) -C .. bitkincoin_qt
